layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  limit: 9
  
snapwidget: 935799

social_media:
  facebook: 8bfda8a533e2ce7b5d7430292eda1574  
  instagram: murbo_  
  linkedin: murbontaitis  
  medium: murbo  
  twitter: murbo_
  website: https://www.urbontaitis.lt  

topics:
  - name: Vue.JS
    web_url: https://github.com/topics/vuejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

  - name: Spock framework
    web_url: http://spockframework.org/
    image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F3%2F36%2FGroovy-logo.svg%2F1200px-Groovy-logo.svg.png

  - name: Spring Boot
    web_url: https://github.com/topics/springboot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png
