layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - pushed
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    - rezervacija
    - env-setup    
    - urbontaitis.github.io 
    - alfred-bitbucket 

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: 8bfda8a533e2ce7b5d7430292eda1574
  # hackerrank: your_username
  instagram: murbo_
  keybase: twx8652
  linkedin: murbontaitis
  # mastodon: your_username
  medium: murbo
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: murbo_
  # unsplash: your_username
  # vk: your_username
  website: https://www.urbontaitis.lt
  # youtube: your_username

topics:
  - name: Vue.JS
    web_url: https://github.com/topics/vuejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Spring Boot
    web_url: https://github.com/topics/springboot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: k8s
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
