name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: ashkantaravati/NuxtToGithubPages@v1.0
      with:
        username: 'urbontaitis'
        reponame: 'urbontaitis.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
